### PR TITLE
Use 2018 edition

### PR DESCRIPTION
**Pull request by bash**

### CODE REVIEW

**Comment by bash** [comment]
ping @withoutboats

**Comment by jplatte** [comment]
This seems like a good idea, sorry for producing conflicts in basically every file by merging other PRs first and updating other parts of the doc examples myself. Could you rebase this PR? (or close and I'll take care of it if you're no longer interested)

**Comment by bash** [comment]
I've rebased the PR. I almost forgot that this PR still exists. :smile:

**Comment by jplatte** [comment]
Thanks! 🙂

**Pull request merged**
