### PR TITLE
Do not insert break for numeric chars

### LINKED ISSUE #3: Unexpected conversion with numerics
I expected `"FIELD_NAME11".to_snake()` to return `"field_name11"`, but instead it's returning `"field_nam_e11"`.

### PR DESCRIPTION
**Pull request by danburkert**
This makes the logic a little more complex to follow, so I'm happy to fix it up if you have any suggestions.  Wanted to keep it to the smallest possible diff for the first cut.  Fixes #3.

### CODE REVIEW

**Comment by withoutboats** [comment]
What does this do for `FieldNamE11`?

**Comment by withoutboats** [comment]
I guess basically what we want the algorithm to do is treat numerics as the same case as the immediately preceding letter

**Comment by danburkert** [comment]
OK I've rewritten the commit.  Instead of treating numeric characters specially, I changed the logic so that instead of treating !c.is_uppercase() as lowercase, it checks for c.is_lowercase() explicitly.  I wrote out some synthetic tests which show the behavior.  I'm not convinced there's a solution that will make everyone happy, but I think this at least an improvement over the current rules.  `FieldNamE11` does indeed map to `field_nam_e11`.

**Comment by danburkert** [comment]
The biggest 'strange' cases remaining are:

```

**Comment by danburkert** [comment]
OK, I pushed a commit which fixes the `99BOTTLES`/`99bottles` discrepancy.  I think this is about as well as I can do.

**Comment by withoutboats** [comment]
I'm going to review this soon, sorry for not looking at it sooner!

**Comment by withoutboats** [comment]
I want to merge this, because I think it implements a correct definition of the word boundaries, but I want the algorithm to be comprehensible to readers also. It seems to me that `previous_is_lowercase` is not the correct name for whatever that variable tracks, because it does not seem to consistenly be set to correspond to the previous character's `this.is_lowercase()` value.

**Comment by danburkert** [comment]
I agree.  More precisely, I think the issue was that I was using two booleans when only three separate states where being tracked.  I've updated the commit to include an explicit tri-state mode, which I think does a better job making it clear what's going on.  The code is now also more similar to the original algorithm (only a single state variable being tracked between scanned characters).

**Comment by withoutboats** [comment]
This looks super clear! Awesome!

**Pull request merged**
